Feature/add vpc
launchbynttdata/tf-aws-module_collection-ecs_platform pull request #2
Opened 2024-06-04 17:34 UTC by aarti-joshi-nttd

2024-06-04 19:30 UTC, debasish-sahoo-nttd requested changes

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
>    description = "The VPC ID of the VPC where infrastructure will be provisioned"
Can you update the description that this is mandatory when create_subnet=false?

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "vpc_name" {
Remove the default, make it null. and update the description that this is required when create_vpc=true

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "vpc_cidr" {
Add similar description as vpc_name. set default to null

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "private_subnet_cidr_ranges" {
Add similar description as vpc_name. set default to []

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "availability_zones" {
Add similar description as vpc_name. set default to []

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "create_vpc" {
update description to specify either this is required or vpc_id variable.

2024-06-04 19:30 UTC, debasish-sahoo-nttd commented on variables.tf
> +variable "vpc_name" {
A suggestion: instead of having multiple variables for vpc details, you can have an object with fields vpc_name, subnet_cidr, subnet_names etc.

2024-06-05 14:34 UTC, ben-vaughan-nttd approved these changes

2024-06-06 17:44 UTC, debasish-sahoo-nttd approved these changes

2024-06-06 18:10 UTC, merged